name: Nitish Parkar
author: Nitish Parkar
url: http://nitishparkar.com/

highlighter: pygments
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-feed
