name: Nitish Parkar
author: Nitish Parkar
url: https://nitishparkar.com/

markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html

sass:
  style: :compressed

defaults:
  - scope:
      path: ""
      type: "book_reviews"
    values:
      layout: "book_review"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed

collections:
  book_reviews:
    output: true
