name: Nitish Parkar
author: Nitish Parkar
url: https://nitishparkar.com/

markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html

sass:
  style: :compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
